Gatekeeper patch.
ndev2/iproute2-final pull request #8
Opened 2017-12-31 20:46 UTC by ndev2

Pull request for the Gatekeeper patch in tc(8) userspace.

2018-07-26 09:39 UTC, ndev2 commented
Hi Michel, the userspace patch is ready from my end, let me know if need to make any changes. Hope the code is good, thanks!

2018-07-26 12:26 UTC, AltraMayor requested changes
**skbprio patch**

2018-07-26 12:26 UTC, AltraMayor commented on man/man8/tc-skbprio.8
> +defense software. It sends traffic based on an assigned priority for the
Improving the first sentence from:
`The SKB Priority Queue is a queueing discipline, intended to be used as an open source DoS defense software.`
to
`The SKB Priority Queue is a queueing discipline intended to prioritize packets during a DoS attack.`

2018-07-26 12:26 UTC, AltraMayor commented on man/man8/tc-skbprio.8
> +defense software. It sends traffic based on an assigned priority for the
Improving the second sentence from:
`It sends traffic based...`
to:
`It prioritizes traffic based...`

2018-07-26 12:26 UTC, AltraMayor commented on tc/q_skbprio.c
> +	fprintf(f, "limit %up ", qopt->limit);
Why do we need the `p` in the format?

2018-07-26 12:26 UTC, AltraMayor commented on man/man8/tc-skbprio.8
> +defense software. It sends traffic based on an assigned priority for the
Could give me push access to this branch so GitHub allows me to edit this text?

2018-07-26 13:37 UTC, ndev2 commented on man/man8/tc-skbprio.8
> +defense software. It sends traffic based on an assigned priority for the
Hi Michel, here's the invite link: https://github.com/ndev2/iproute2-final/invitations

2018-07-26 13:39 UTC, ndev2 commented on tc/q_skbprio.c
> +	fprintf(f, "limit %up ", qopt->limit);
The `p` is to symbolize that it is in packets (as opposed to bytes). Should we change this?

2018-07-27 11:51 UTC, AltraMayor commented on tc/q_skbprio.c
> +	fprintf(f, "limit %up ", qopt->limit);
As you can read in Cong's comment to Qiaobin's patch (https://patchwork.ozlabs.org/patch/941073/): "Please align the output syntax with the input syntax. Traditionally iproute2 command output can be just used for input, even though
it is no longer true now."

So the `p` above is breaking this alignment.

2018-07-27 13:33 UTC, AltraMayor commented on man/man8/tc-skbprio.8
> +defense software. It sends traffic based on an assigned priority for the
I've edited the text. Please merge my patches into yours and review the text as well as the format of the man page.

2018-07-27 22:55 UTC, ndev2 commented
Hi @AltraMayor , I've pulled and rebased with somw changes, hope the code is good. Thanks!

2018-07-28 13:01 UTC, AltraMayor commented
This patch is ready to go upstream.

2018-07-28 18:02 UTC, merged